# Generated by Django 5.0.6 on 2024-07-10 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
