# Generated by Django 4.2 on 2024-07-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_groups_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_joined",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
