# Generated by Django 5.0.6 on 2024-07-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
            },
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="published",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="views_count",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(verbose_name="Содержимое"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="preview_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_previews/", verbose_name="Превью"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
    ]
