# Generated by Django 5.0.6 on 2024-07-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogpost_options_remove_blogpost_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="preview_image",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(blank=True, null=True, upload_to="blog/previews/"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
