# Generated by Django 5.0.6 on 2024-07-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpost_options_remove_blogpost_preview_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="preview",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="preview_image",
            field=models.ImageField(default=1, upload_to="blog/images/"),
            preserve_default=False,
        ),
    ]
