# Generated by Django 5.0.6 on 2024-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_remove_blogpost_preview_blogpost_preview_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="preview_image",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="preview",
            field=models.ImageField(
                default="default_preview.jpg", upload_to="blog_previews/"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
