# Generated by Django 5.0.6 on 2024-07-10 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_blogpost_preview_image_blogpost_preview_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="preview",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="slug",
        ),
    ]
