# Generated by Django 5.0.6 on 2024-07-10 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_blogpost_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
