# Generated by Django 5.0.6 on 2024-07-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_blogpost_created_at_blogpost_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="is_published",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
