# Generated by Django 5.0.6 on 2024-07-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_alter_article_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью статьи",
                null=True,
                upload_to="article_previews/",
                verbose_name="Превью",
            ),
        ),
    ]
