# Generated by Django 5.0.6 on 2024-07-12 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("off_published", "can remove published"),
                    ("change_description", "can change description"),
                    ("change_category", "can change category"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
