# Generated by Django 5.0.6 on 2024-07-12 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_version_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="Is Current Version"),
        ),
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=100, verbose_name="Version Name"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.CharField(max_length=20, verbose_name="Version Number"),
        ),
    ]
