# Generated by Django 5.0.6 on 2024-07-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_version_is_current_alter_version_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="Активная версия"),
        ),
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=100, verbose_name="Название версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.CharField(max_length=20, verbose_name="Номер версии"),
        ),
    ]
