# Generated by Django 4.2 on 2024-07-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0006_alter_version_is_current_alter_version_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="version",
            name="delete_version",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="version",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.CharField(max_length=100),
        ),
    ]
