# Generated by Django 5.0.6 on 2024-07-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_blogpost_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="preview_image",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="views_count",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
